/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.pacientes;

import controlador.PacienteControlador;
import javax.swing.table.DefaultTableModel;
import modelo.PacienteModelo;

/**
 *
 * @author HP
 */
public class Listado extends javax.swing.JInternalFrame {
public DefaultTableModel tableModel=new DefaultTableModel();
    PacienteControlador pc= PacienteControlador.getInstancia();
    public Listado() {
        initComponents();
        
 tbl_listado.setModel(tableModel);
        String columnas[]={"CEDULA","NOMBRES","EDAD","SEXO"};
        tableModel.setColumnIdentifiers(columnas);
        
        cargarListadoPacientes();
     
    }
private void cargarListadoPacientes(){
       for(PacienteModelo pm : pc.listadoCompleto()) {
           Object[]fila={pm.getCedula(),pm.getNombre(),pm.getEdad(),pm.getSexo()};
            tableModel.addRow(fila);
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbuscarporcedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listado = new javax.swing.JTable();

        jLabel1.setText("Buscar por cedula");

        txtbuscarporcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarporcedulaKeyReleased(evt);
            }
        });

        tbl_listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_listado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscarporcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbuscarporcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarporcedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarporcedulaKeyReleased
      tableModel.setRowCount(0);
        String cedula=txtbuscarporcedula.getText();
      
        for(PacienteModelo pm : pc.listadoCompletoPorCedula(cedula)) {
           Object[]fila={pm.getCedula(),pm.getNombre(),pm.getEdad(),pm.getSexo()};
            tableModel.addRow(fila);
        }
    }//GEN-LAST:event_txtbuscarporcedulaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_listado;
    private javax.swing.JTextField txtbuscarporcedula;
    // End of variables declaration//GEN-END:variables
}
