/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista.citas;

import controlador.CitaControlador;
import javax.swing.table.DefaultTableModel;
import modelo.CitaModelo;

/**
 *
 * @author HP
 */
public class Listado extends javax.swing.JInternalFrame {
public DefaultTableModel tableModel=new DefaultTableModel();
    CitaControlador cc= CitaControlador.getInstancia();
    /**
     * Creates new form Listado
     */
    public Listado() {
        initComponents();
        tblCita.setModel(tableModel);
        String columnas[]={"PACIENTE","ESPECIALIDAD","MEDICO","DESCRIPCION","FECHA","HORA"};
        tableModel.setColumnIdentifiers(columnas);
        
        cargarListadoCita();
    }
private void cargarListadoCita() {
    for (CitaModelo cm : cc.listadoCompleto()) {
        Object[] fila = {
            cm.getPaciente(),      // Paciente
            cm.getEspecialidad(),  // Especialidad
            cm.getMedico(),        // Médico
            cm.getDescripcion(),   // Descripción
            cm.getFecha(),         // Fecha
            cm.getHora()           // Hora
        };
        tableModel.addRow(fila);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCita = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPorHora = new javax.swing.JTextField();

        tblCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCita);

        jLabel1.setText("INGRESE LA HORA PARA BUSCAR");

        txtBuscarPorHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPorHoraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPorHoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorHoraKeyReleased
            tableModel.setRowCount(0);
        String hora=txtBuscarPorHora.getText();
      
        for(CitaModelo cm : cc.listadoCompletoPorHora(hora)) {
           Object[]fila={cm.getPaciente(),cm.getEspecialidad(),cm.getMedico(),cm.getDescripcion(),cm.getFecha(),cm.getHora()};
            tableModel.addRow(fila);
        }
    }//GEN-LAST:event_txtBuscarPorHoraKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCita;
    private javax.swing.JTextField txtBuscarPorHora;
    // End of variables declaration//GEN-END:variables
}
